# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70946345fc6633a7ec4db74541ba675b1ef3e689f17abad36294fa10b1de1f9d7341f50192d6173d74bdc2c3bc4f0eae6de3c806fdb616d8c4f6c02d05a45095

test:
  secret_key_base: 96cb22cc58f70b0f477ce3dc4821a32917266f6b2e7a24f26f654c210928ce65dbdada702838a4fc7cad97ce10392286635451b4fa0e8bece2beff1debc07363

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
